### PR TITLE
defconfig: Enable TTL Target

### PR DESCRIPTION
**Pull request by MrArtemSid**
Some network providers requires fixed TTL to be able to share hotspot

### CODE REVIEW

**Comment by xboxfanj** [comment]
Thanks for submitting this.

I'm ok with the change, but we do not accept GitHub pull requests because we use Gerrit for code review and this would bring GitHub and Gerrit out of sync.

Can you please submit it to https://gerrit.aospa.co?

**Comment by MrArtemSid** [comment]
Thanks for answering. Can u please add this change by yourself, cause I'm not at pc for a week?

**Comment by xboxfanj** [comment]
ok

**Comment by MrArtemSid** [comment]
Thanks you again :)

**Pull request closed without merging**
